### PR TITLE
DFD 4

### PR DESCRIPTION
**Pull request by IlanTulepov**

### CODE REVIEW

**Comment by IlanKro** [comment]
‫בתאריך יום א׳, 11 בנוב׳ 2018 ב-12:22 מאת ‪IlanTulepov‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by IlanKro** [comment]
Can't connect DB to User.
Need to add process for information fetching.
Need to add process for input validation.

**Comment by IlanKro** [comment]
missing user index
missing label for arrow

**Comment by IlanTulepov** [comment]
@soryy708 No idea how to implement the username check process correctly (D2- users), should I change all the calls to "input"? and the requests to "data"? and so on?

**Comment by soryy708** [comment]
- Customer missing index
- Text is overflowing
- 4.3, 4.2 - לא לשון ציווי

**Pull request merged**
