### PR TITLE
Additions

### PR DESCRIPTION
**Pull request by IlanKro**
Closed the other commit, and cleaned up the DFDs 2,7,8

### CODE REVIEW

**Comment by soryy708** [comment]
Why does `6 Log in` send to `D1 tickets` whether log in is authorized?
`2.1b.1 authenticate the user` to `D1 tickets` - Arrow has an action rather than data. Should probably be an extra circle between them with proper data flow.

**Comment by IlanKro** [comment]
updated DFD2 according to the request of Mr. Robinson

**Comment by soryy708** [comment]
@IlanKro Not all points were covered.

**Comment by soryy708** [comment]
DFD 7:
Arrows have labels with לשון ציווי.
Not good; they should be data, not processes.

**Comment by StavLobel** [comment]
Finished fixes on DFD8 for your review .

**Pull request merged**
